### PR TITLE
Fix: generated qnt_* primitives support m in [1, 7]

### PR DESCRIPTION
**Pull request by maciekcc**
One of the generated primitives (qnt_* requantization code) mistakenly assumed that m is greater or equal to 8. This fix makes sure that all m > 0 are supported.

### CODE REVIEW

**Comment by bjacob** [comment]
Did you intend to make a more descriptive commit message?

**Comment by maciekcc** [comment]
The generated qnt_* primitives contain two segments of code:
-- the main loop that goes through the result array in 8 element increments, and
-- the leftover code that takes care of the rest in case m is not a multiply of 8

Previously the main loop would execute at least once. I have added a jump straight to the leftover code in case when m < 8.

**Comment by bjacob** [comment]
Great, thanks for the explanation. I meant to ask, right now the commit message seems to be just "wip", how about updating it with at least a one-line summary?

**Comment by maciekcc** [comment]
Ah, ok, done. Added a comment to the original commit.

**Comment by bjacob** [comment]
Many thanks!

**Pull request merged**
