### PR TITLE
Use mutexes instead of memory barriers in the profiler.

### PR DESCRIPTION
**Pull request by mjmatthews**
Ok, I believe this should be a proper pull request from my forked gemmlowp repository. 
We've looked at all these changes together, and I've built and tested it successfully. Hope it works just as well for you. Let me know if you have any issues.

-Mark

### CODE REVIEW

**Comment by bjacob** [comment]
Thanks, great improvements!

Regarding the CLA whine, this shouldn't be needed for you as you're part of Google, so I suppose the only thing that you should have to do is to join the Google organization on GitHub with this identity.

**Comment by mjmatthews** [comment]
It sounds like "...maybe you used a different email address in the git commits..." is implying that my e-mail (mjmatthews@google.com) should be in the git commits somehow, perhaps as a comment? Any idea how I satisfy this condition?

**Comment by bjacob** [comment]
This is saying that this email address should be the identity ("author" filed) under which your commits are made.

See:  git commit --author=....

(use with --amend to fix your existing commits)

and

https://help.github.com/articles/setting-your-username-in-git/

**Comment by mjmatthews** [comment]
Ok, so I think this should finally fix the "whines" regarding CLA. My apologies for polluting the commit history with extra commits. I think (fingers crossed) I finally have it fixed for good.

**Pull request merged**
