### PR TITLE
Simplify WorkersPool API.

### PR DESCRIPTION
**Pull request by andreasgal**

### CODE REVIEW

**Comment by bjacob** [comment]
@maciekcc , do you want to take the first pass at reviewing this, since this touches meta/ code, and had comments on the internal/ part of the previous PR ? Once you've taken a look, I'll do a second review of the internal/ part.

**Comment by andreasgal** [comment]
I pushed a rebased version to trigger the CI build and checks (in part as a test of that new feature).

**Comment by andreasgal** [comment]
@maciekcc: ping

**Comment by maciekcc** [comment]
I am having problems compiling this patch. Can you please try if the tests work on your setup:

./scripts/test-android.sh test/correctness_meta_gemm.cc
./scripts/test-android.sh test/benchmark_meta_gemm.cc eight_bit_int_gemm/eight_bit_int_gemm.cc -O3 -DNDEBUG
./scripts/test-android.sh test/benchmark.cc

The script should build a a binary, adb push it to a plugged in phone, and finally run it. You will need to set CXX to point at your toolchains c++ compiler.

I am using: /home/maciekc/toolchains/arm-android-21/bin/arm-linux-androideabi-g++ (gcc version 4.9 20150123)

**Comment by andreasgal** [comment]
Thanks! I'll try that and also add this to CI if possible.

**Comment by andreasgal** [comment]
The patch updates CI to build on Android and run 2 of the tests via the emulator. I am not running correctness_meta_gemm on each check-in. The "big" part of the test is just too slow. If you are willing to split up that test we could run at least run the small part of it. I also fixed the bugs you were probably seeing (I think). @maciekcc

**Comment by andreasgal** [comment]
benchmark_meta_gemm is super slow too, we may want to disable that in automation as well

**Comment by maciekcc** [comment]
The meta/ part looks good to me. Thanks for fixing the compile issues, and setting up the emulator.

**Comment by bjacob** [comment]
@maciekcc, can you also review the internal/multi_thread_gemm.h changes at least insofar as they interact with meta/ ?

**Comment by maciekcc** [comment]
internal also looks fine. One thing bothers me: previously the ownership of the task was passed through StartWorker and was. Now, it is not obvious that the tasks in the vector will get deleted when you call Execute -- you end up with dangling pointers. Please consider deleting the tasks where they are created, outside Execute (or you can use unique_ptr's for the vector and tasks, but I think I would prefer this less).

**Comment by bjacob** [comment]
I think that is addressed by the code comment:
+    // Cleanup tasks (best to do this from the same thread that allocated
 +    // the memory).
Sounds fair to me, I'll merge, we can continue the discussion afterwards as needed.

**Pull request merged**
