### PR TITLE
Fix #136 (test_blocking_counter)

### LINKED ISSUE #136: [BUG] Failed to build on several architectures
Overview: https://buildd.debian.org/status/package.php?p=gemmlowp&suite=experimental

Failed on i386 https://buildd.debian.org/status/fetch.php?pkg=gemmlowp&arch=i386&ver=0%7E20180308-gf59a96b-1&stamp=1527673668&raw=0

Failed on armel https://buildd.debian.org/status/fetch.php?pkg=gemmlowp&arch=armel&ver=0%7E20180308-gf59a96b-1&stamp=1527747448&raw=0

mips https://buildd.debian.org/status/fetch.php?pkg=gemmlowp&arch=mips&ver=0%7E20180308-gf59a96b-1&stamp=1527656602&raw=0

powerpc https://buildd.debian.org/status/fetch.php?pkg=gemmlowp&arch=powerpc&ver=0%7E20180308-gf59a96b-1&stamp=1527657665&raw=0

The errors look the same:
```
E: Build killed with signal TERM after 150 minutes of inactivity
```
Deadlock triggered in `test_blocking_counter`?

### PR DESCRIPTION
**Pull request by alexfru**
Note the change in the company/contributors.

### CODE REVIEW

**Comment by bjacob** [comment]
Thanks! Now GitHub says the cla/google check still fails with "CLAs are signed, but unable to verify author consent".  No idea what this means.  Do you need me to hunt down someone who could help?

Regarding the code, this looks great, perhaps you could add a comment so that people remember in the future why this is done and don't revert it thinking it's not needed anymore.

**Comment by bjacob** [comment]
...nevermind, there is such a comment. Thanks!

**Comment by alexfru** [comment]
@bjacob, Here's what I'm seeing on that page:

> Contributor License Agreements
> 
> We don't have any individual agreements on file for you.
> Corporate Agreements
> 
> You are covered by the following corporate agreements:
> 
> Agreement | Name | Date Signed
> two older agreements
> Google Corporate CLA | Wave Computing, Inc. | Mar 19, 2018 12:04 PDT
> 
> Sign a new agreement:
> 
> You plan to submit contributions on behalf of:
> \[Only Yourself\] \[Your Employer\]
> 

So, I'm not sure if I (or someone else over here) needs to click one of those two buttons at the bottom and complete yet another form.

**Comment by bjacob** [comment]
I am asking for help internally about this.

**Pull request merged**
